# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometricmodel',
            name='file',
            field=models.FileField(upload_to='data'),
        ),
    ]
