# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicalinput',
            name='Bs_c',
            field=models.FloatField(help_text='Constante de compresión de Byerlee (MPa)', verbose_name='Bs (c)'),
        ),
        migrations.AlterField(
            model_name='mechanicalinput',
            name='Bs_t',
            field=models.FloatField(help_text='Constante de tensión de Byerlee (MPa)', verbose_name='Bs (t)'),
        ),
        migrations.AlterField(
            model_name='mechanicalinput',
            name='Ci',
            field=models.ForeignKey(help_text='Modelo reológico para la corteza inf.', on_delete=django.db.models.deletion.CASCADE, related_name='ci', to='matrices.RheologicModel', verbose_name='C.I.'),
        ),
        migrations.AlterField(
            model_name='mechanicalinput',
            name='Cs',
            field=models.ForeignKey(help_text='Modelo reológico para la corteza sup.', on_delete=django.db.models.deletion.CASCADE, related_name='cs', to='matrices.RheologicModel', verbose_name='C.S.'),
        ),
        migrations.AlterField(
            model_name='mechanicalinput',
            name='Ml',
            field=models.ForeignKey(help_text='Modelo reológico para el manto litosférico', on_delete=django.db.models.deletion.CASCADE, related_name='ml', to='matrices.RheologicModel', verbose_name='M.L.'),
        ),
        migrations.AlterField(
            model_name='mechanicalinput',
            name='R',
            field=models.FloatField(help_text='Constante universal de gases (J mol-1 K-1)', verbose_name='R'),
        ),
        migrations.AlterField(
            model_name='mechanicalinput',
            name='e',
            field=models.FloatField(help_text='Strain rate (s-1)', verbose_name='e'),
        ),
        migrations.AlterField(
            model_name='mechanicalinput',
            name='mx_s',
            field=models.FloatField(help_text='Máximo stress disponible (MPa)', verbose_name='S max.'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='D2',
            field=models.FloatField(help_text='Constante de proporcionalidad adimensional', verbose_name='D2'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='EF',
            field=models.FloatField(help_text='Edad de la corteza oceánica en la fosa (Ma)', verbose_name='EF'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='EF_lat',
            field=models.BooleanField(help_text='¿Usar EF en función de la latitud?', verbose_name='EF = f(lat)'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='G_a',
            field=models.FloatField(help_text='Gradiente adiabático (K/m)', verbose_name='Ga'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='H_ci',
            field=models.FloatField(help_text='Calor radiogénico corteza inf. (W/m3)', verbose_name='H (ci)'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='H_cs',
            field=models.FloatField(help_text='Calor radiogénico corteza sup. (W/m3)', verbose_name='H (cs)'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='H_ml',
            field=models.FloatField(help_text='Calor radiogénico manto litosférico (W/m3)', verbose_name='H (ml)'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='H_z',
            field=models.BooleanField(help_text='¿Usar H en función de la profundidad?', verbose_name='H = f(z)'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='K_ci',
            field=models.FloatField(help_text='Conductividad térmica corteza inf. (W/mK)', verbose_name='K (ci)'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='K_cs',
            field=models.FloatField(help_text='Conductividad térmica corteza sup. (W/mK)', verbose_name='K (cs)'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='K_ml',
            field=models.FloatField(help_text='Conductividad térmica manto litosférico (W/mK)', verbose_name='K (ml)'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='K_z',
            field=models.BooleanField(help_text='¿Usar K en función de la profundidad?', verbose_name='K = f(z)'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='T_p',
            field=models.FloatField(help_text='Temperatura potencial del manto (C)', verbose_name='Tp'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='V',
            field=models.FloatField(help_text='Velocidad de convergencia (m/Ma)', verbose_name='V'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='b',
            field=models.FloatField(help_text='Parametro adimensional', verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='d_rad',
            field=models.FloatField(help_text='Decaimiento radiogénico (km)', verbose_name='Drad'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='dip',
            field=models.FloatField(help_text='Ángulo de subduccion', verbose_name='dip'),
        ),
        migrations.AlterField(
            model_name='thermalinput',
            name='kpa',
            field=models.FloatField(help_text='Difusividad térmica (m2/s)', verbose_name='kpa'),
        ),
    ]
