# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0002_auto_20170625_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermalinput',
            name='EF',
            field=models.FloatField(blank=True, help_text='Edad de la corteza oceánica en la fosa (Ma)', verbose_name='EF'),
        ),
    ]
